// <auto-generated />
using System;
using MQEL.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MQEL.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260623133545_SnapshotName")]
    partial class SnapshotName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MQEL.Core.Model.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CastleClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastleRenovationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InventorySeq")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Privileges")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedHeroClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MQEL.Core.Model.Castle", b =>
                {
                    b.Property<long>("CastleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastleHeartRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConstructionPoints")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CastleId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Castles");
                });

            modelBuilder.Entity("MQEL.Core.Model.CastleBuilding", b =>
                {
                    b.Property<long>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuildingIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomZoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("RoomId");

                    b.ToTable("CastleBuildings");
                });

            modelBuilder.Entity("MQEL.Core.Model.CastleRoom", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CastleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomId");

                    b.HasIndex("CastleId");

                    b.ToTable("CastleRooms");
                });

            modelBuilder.Entity("MQEL.Core.Model.CompletedAssignment", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "AssignmentId");

                    b.ToTable("CompletedAssignments");
                });

            modelBuilder.Entity("MQEL.Core.Model.Hero", b =>
                {
                    b.Property<long>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId");

                    b.HasIndex("AccountId", "HeroClass")
                        .IsUnique();

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroConsumable", b =>
                {
                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId", "TemplateId");

                    b.ToTable("HeroConsumables");
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroGearItem", b =>
                {
                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArchetypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DyeTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stat0")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat1")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat2")
                        .HasColumnType("REAL");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId", "Slot");

                    b.ToTable("HeroGear");
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroInventoryItem", b =>
                {
                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchetypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DyeTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stat0")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat1")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat2")
                        .HasColumnType("REAL");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId", "Slot");

                    b.ToTable("HeroInventory");
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroSpell", b =>
                {
                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroId", "SpellId");

                    b.ToTable("HeroSpells");
                });

            modelBuilder.Entity("MQEL.Core.Model.InventoryItem", b =>
                {
                    b.Property<string>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchetypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DyeTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Stat0")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat1")
                        .HasColumnType("REAL");

                    b.Property<double>("Stat2")
                        .HasColumnType("REAL");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectId");

                    b.HasIndex("AccountId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("MQEL.Core.Model.Objective", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastStatusUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "ObjectiveId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("MQEL.Core.Model.Wallet", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Capacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "CurrencyType");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("MQEL.Core.Model.Castle", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithOne("Castle")
                        .HasForeignKey("MQEL.Core.Model.Castle", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.CastleBuilding", b =>
                {
                    b.HasOne("MQEL.Core.Model.CastleRoom", null)
                        .WithMany("Buildings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.CastleRoom", b =>
                {
                    b.HasOne("MQEL.Core.Model.Castle", null)
                        .WithMany("Rooms")
                        .HasForeignKey("CastleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.CompletedAssignment", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithMany("CompletedAssignments")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.Hero", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithMany("Heroes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroConsumable", b =>
                {
                    b.HasOne("MQEL.Core.Model.Hero", null)
                        .WithMany("Consumables")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroGearItem", b =>
                {
                    b.HasOne("MQEL.Core.Model.Hero", null)
                        .WithMany("Gear")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroInventoryItem", b =>
                {
                    b.HasOne("MQEL.Core.Model.Hero", null)
                        .WithMany("Inventory")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.HeroSpell", b =>
                {
                    b.HasOne("MQEL.Core.Model.Hero", null)
                        .WithMany("Spells")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.InventoryItem", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithMany("Inventory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.Objective", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithMany("Objectives")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.Wallet", b =>
                {
                    b.HasOne("MQEL.Core.Model.Account", null)
                        .WithMany("Wallets")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MQEL.Core.Model.Account", b =>
                {
                    b.Navigation("Castle");

                    b.Navigation("CompletedAssignments");

                    b.Navigation("Heroes");

                    b.Navigation("Inventory");

                    b.Navigation("Objectives");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("MQEL.Core.Model.Castle", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MQEL.Core.Model.CastleRoom", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("MQEL.Core.Model.Hero", b =>
                {
                    b.Navigation("Consumables");

                    b.Navigation("Gear");

                    b.Navigation("Inventory");

                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
